# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6218\u961f\u540d')),
                ('phone_number', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('slogan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User', verbose_name='\u6218\u961f\u961f\u957f')),
            ],
        ),
        migrations.CreateModel(
            name='CombatTeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('combat_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combat_team.CombatTeam', verbose_name='\u6218\u961f')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User', verbose_name='\u6218\u961f\u4eba\u5458')),
            ],
        ),
    ]
