# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatteam',
            name='introduce',
            field=models.TextField(null=True),
        ),
    ]
