# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('combat_team', '0003_combatteammembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True, verbose_name='\u5907\u6ce8')),
                ('request_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.User', verbose_name='\u7533\u8bf7\u4eba')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combat_team.CombatTeam', verbose_name='\u6218\u961f')),
            ],
        ),
    ]
