# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_team', '0004_teamrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrequest',
            name='remark',
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
