# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_team', '0005_auto_20180428_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u6e38\u620f\u7c7b\u578b')),
                ('people_number', models.IntegerField(max_length=20, verbose_name='\u9700\u8981\u4eba\u6570')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
    ]
