# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_team', '0006_gametype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='people_number',
            field=models.IntegerField(verbose_name='\u9700\u8981\u4eba\u6570'),
        ),
    ]
