# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-01 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_team', '0007_auto_20180430_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatteam',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='combat_team.GameType', verbose_name='\u6e38\u620f\u7c7b\u578b'),
        ),
    ]
