# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-29 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_team', '0008_combatteam_type'),
        ('combat_team', '0002_combatteam_introduce'),
    ]

    operations = [
    ]
